from Bio.PDB import*
pdbl = PDBList() 
pdbl.retrieve_pdb_file('5UGB', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('3BEL', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('2GS2', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('2GS6', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('4ZJV', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('1M17', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('1M14', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('4ZAU', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('6JZ0', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('3W2S', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('4LI5', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('3W32', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('4L23', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('5CAV', pdir = '.', file_format = 'pdb')
pdbl = PDBList() 
pdbl.retrieve_pdb_file('3VJO', pdir = '.', file_format = 'pdb')